targets:
  $default:
    builders:
      json_serializable:
        options:
          explicit_to_json: true
      freezed:
        options:
          build_extensions:
            '^lib/{{dir}}/{{file}}.dart': 'lib/{{dir}}/freezed/{{file}}.freezed.dart'
      source_gen:combining_builder:
        options:
          build_extensions:
            '^lib/{{dir}}/{{file}}.dart': 'lib/{{dir}}/generated/{{file}}.g.dart'
